export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function SalesLayout({ children }) {
    return (
        <div>
            {children}
            $$$$$
        </div>
    );
}
